name: sih2022
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  video_player:
  flutter_local_notifications: ^9.5.3+1
  path_provider: ^2.0.11
  http: ^0.13.4
  rxdart: ^0.27.4
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/launcher.png
    - assets/
    - assets/video1.mp4
  uses-material-design: true